version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      deps-solid:
        applies-to: "version-updates"
        dependency-type: "production"
        patterns:
          - "@solidjs/router"
          - "solid-js"

      dev-deps-build:
        applies-to: "version-updates"
        dependency-type: "development"
        patterns:
          - "sass-embedded"
          - "vite"
          - "vite-plugin-solid"
          - "typescript"

      dev-deps-test:
        applies-to: "version-updates"
        dependency-type: "development"
        patterns:
          - "@testing-library/*"
          - "@solidjs/testing-library"
          - "happy-dom"
          - "vitest"
