name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: "${{ github.workflow }} - ${{ github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        script:
          - format:check
          - lint
          - typecheck
          - build
          - test

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Dependencies
        uses: marcalexiei/github-actions/.github/actions/setup-node-and-pnpm@f27a68a73a799c79d7158cf4a98d7e3d5e8e23be # v1.1.0

      - name: Run ${{ matrix.script }}
        run: pnpm run ${{ matrix.script }}
